name: NewTMSv8
version: '${project.version}'
main: me.cyperion.ntms.NewTMSv8
softdepend: [Vault,Essentials,PlaceholderAPI]
api-version: '1.20'
commands:
  admin:
    description: 管理員專用指令，用於開發插件的。
    usage: /admin
  warp:
    description: 可以傳送到 資源界/床重生點/台灣
    usage: /warp <rs/bed/tw>
  enderchest:
    description: 可以隨時隨地開啟終界箱
